use Irssi;
use Irssi::Irc;
use strict;
use vars qw($VERSION %IRSSI);

$VERSION = "0.0.1";
%IRSSI   = (
    authors     => 'Tiago Sousa (aka mirage) & falso',
    contact     => 'mirage\@kaotik.org',
    name        => 'slogan',
    description => 'Prints slogans for the given keyword',
    license     => 'GPLv3',
    url         => 'http://',
);

my @slogans = (
    "%string% - a class of it's own",
    "%string% - a safe place in an unsafe world!",
    "%string% - as good as it gets!",
    "%string% - be prepared.",
    "%string% - be ready.",
    "%string% - empowering people.",
    "%string% - enjoy the difference.",
    "%string% - first class!",
    "%string% - forget the rest.",
    "%string% - get ready.",
    "%string% - go for it!",
    "%string% - go for the game.",
    "%string% - If you love %string%.",
    "%string% - it's like heaven!",
    "%string% - Just do it.",
    "%string% - living innovation",
    "%string% - now!",
    "%string% - once you have it, you love it.",
    "%string% - One name. One legend.",
    "%string% - play it!",
    "%string% - simplified!",
    "%string% - spice up your life.",
    "%string% - The Revolution.",
    "%string% - Think different.",
    "%string% - to feel free!",
    "%string% - today and tomorrow.",
    "%string% - what more could you want?",
    "%string% - Xtending service.",
    "%string% - Yabba Dabba Duh!",
    "%string% - You see this name, you think dirty.",
    "%string% - your game.",
    "%string% - Your personal entertainer.",
    "%string% after a long day.",
    "%string% beat.",
    "%string% brings out the best.",
    "%string% can do.",
    "%string% Dreamteam.",
    "%string% empowers you.",
    "%string% evolution.",
    "%string% extra dry.",
    "%string% for a better future.",
    "%string% for a professional image.",
    "%string% for everybody.",
    "%string% for everyone.",
    "%string% for me!",
    "%string% for president.",
    "%string% for the masses.",
    "%string% for you!",
    "%string% for your health.",
    "%string% for your kids!",
    "%string% for your life.",
    "%string% forever.",
    "%string% groove.",
    "%string% innovate your world.",
    "%string% inside you.",
    "%string% is a female force.",
    "%string% is a never ending story.",
    "%string% is back.",
    "%string% is better than chocolate.",
    "%string% is forever.",
    "%string% is good for you.",
    "%string% is inspiration.",
    "%string% is my passion.",
    "%string% is my sport.",
    "%string% is my world.",
    "%string% is our middle name.",
    "%string% is rolling, the others are stoned.",
    "%string% is the best!",
    "%string% is the only way to be happy.",
    "%string% is the sound of the future.",
    "%string% is what the world was waiting for.",
    "%string% is your friend.",
    "%string% is your safe place in an unsafe world!",
    "%string% it's a kind of magic.",
    "%string% keeps going, and going, and going...",
    "%string% kicks ass.",
    "%string% know-how.",
    "%string% lifestyle",
    "%string% loves you.",
    "%string% makes dreams come true.",
    "%string% makes me hot.",
    "%string% makes your day.",
    "%string% moments.",
    "%string% never die.",
    "%string% never lies.",
    "%string% never sleeps.",
    "%string% nonstop.",
    "%string% on the outside, tasty on the inside.",
    "%string% online.",
    "%string% only.",
    "%string% rocks.",
    "%string% rules.",
    "%string% strikes back.",
    "%string% takes good care of you.",
    "%string% values.",
    "%string% wanted.",
    "%string% will be for you what you want it to be.",
    "%string% will do anything for you.",
    "%string% wonder.",
    "%string%'s got it all!",
    "%string%'s like heaven.",
    "%string%, better than sex.",
    "%string%, created by nature.",
    "%string%, good.",
    "%string%, i want it all.",
    "%string%, in touch with tomorrow.",
    "%string%, it's as simple as that!",
    "%string%, just the best.",
    "%string%, love it or leave it.",
    "%string%, one for all.",
    "%string%, pure lust.",
    "%string%, since 1845.",
    "%string%, so what!",
    "%string%, stay in touch.",
    "%string%, the clever way.",
    "%string%, the freshmaker.",
    "%string%, the original.",
    "%string%, the real thing.",
    "%string%, the secret of women.",
    "%string%, the smart choice.",
    "%string%, there's no better way.",
    "%string%, this is it!",
    "%string%, to hell with the rest.",
    "%string%, where success is at home.",
    "%string%, whiter than the whitest!",
    "%string%, you'll love it!",
    "%string%, you've got it!",
    "%string%, your family will love you.",
    "%string%, your specialist.",
    "%string%, your way!",
    "%string%. Impossible is nothing.",
    "%string%. Making people sucessful in a changing world.",
    "%string%. See more. Do more.",
    "%string%. The power on your side.",
    "%string%. We build smiles.",
    "%string%... whatever you want.",
    "%string%? Yes please.",
    "%string%? You bet.",
    "%string%rific.",
    "%string%tastic!",
    "3...  2...  1... %string%.",
    "A day with %string%.",
    "All you need is %string%.",
    "Always the real thing, always %string%.",
    "And on the eighth day, god created %string%.",
    "Anyone can handle %string%.",
    "Are you ready for %string%?",
    "Be alive with %string%.",
    "Be inspired by %string%.",
    "Be part of %string%.",
    "Be young, have fun, taste %string%.",
    "Bigger. Better. %string%.",
    "Break through with %string%.",
    "Buy %string% now!",
    "Call a friend, call %string%.",
    "Can you feel %string%?",
    "Can you feel it? %string%.",
    "Connect with %string%.",
    "Discover the world of %string%.",
    "Do it with %string%.",
    "Do you know %string%?",
    "Don't forget your %string%.",
    "Don't get in the way of %string%.",
    "Don't mess with %string%.",
    "Don't play with fire, play with %string%.",
    "Don't worry, %string% takes care.",
    "Easy %string%.",
    "Endless possibilities with %string%.",
    "Enjoy %string%.",
    "Every %string% has a story.",
    "Everyone loves %string%.",
    "Everyone should believe in %string%.",
    "Everything is simple with %string%.",
    "Feel good with %string%.",
    "Feel it - %string%!",
    "Feel the magic of %string%.",
    "Firstclass %string%!",
    "Follow your %string%.",
    "Food or %string%? I'll have %string%.",
    "For the love of %string%.",
    "Free %string%.",
    "Funky %string%.",
    "Get me my %string%.",
    "Go far with %string%.",
    "Go farther with %string%.",
    "Go to heaven with %string%.",
    "God made %string%.",
    "Good to know %string%.",
    "Halleluja, it's a %string%.",
    "Have a break, have a %string%.",
    "Heal the world with %string%.",
    "hhmmmmm... %string%.",
    "High life with %string%.",
    "I believe in %string%.",
    "I can't believe it's %string%.",
    "I fall for %string%.",
    "I lost weight with %string%.",
    "I love %string%.",
    "I quit smoking with %string%.",
    "I trust %string%.",
    "I want %string% and I want it now.",
    "I want more, I want %string%.",
    "I wish i had a %string%.",
    "I wish i was a %string%.",
    "I wouldn't leave the house without %string%.",
    "I'd do anything for %string%.",
    "I'd sleep with %string%.",
    "I'd walk a mile for %string%.",
    "Inspired by %string%.",
    "It must be %string%.",
    "It's my %string%!",
    "It's not a dream. %string% is real!",
    "It's time to think about %string%.",
    "It's your %string%!",
    "Jesus loves %string%.",
    "Just %string%.",
    "Keep going well, keep going %string%.",
    "Kick ass with %string%!",
    "Let your %string% flow.",
    "Let's %string%!",
    "Let's talk about %string%.",
    "Life's beautiful with %string%.",
    "Live %string%.",
    "Long life %string%.",
    "Lucky %string%.",
    "Made by %string%.",
    "Make the world a better place with %string%.",
    "Make yourself at home with %string%.",
    "My %string% and me.",
    "My %string% beats everything.",
    "My %string% is mine.",
    "My %string%, your %string%, %string% for all!",
    "My way is %string%.",
    "Naughty little %string%.",
    "Next stop, %string%.",
    "No %string%, no kiss.",
    "No need to worry with %string%.",
    "Nobody does it like %string%.",
    "Nobody doesn't like %string%.",
    "Nonstop %string%.",
    "Nothing is faster than %string%.",
    "Nothing to worry about with %string%.",
    "Oh my goddess, it's a %string%.",
    "Oh my gods, it's a %string%.",
    "Once %string%, always %string%.",
    "One goal, one passion - %string%.",
    "Ooh la la, %string%.",
    "Passion for %string%.",
    "Play %string%, start living.",
    "Praise %string%.",
    "Pure %string%. Pure Power.",
    "Saved by %string%!",
    "Say %string%.",
    "Say it with %string%.",
    "See the world with %string%.",
    "See you at %string%.",
    "Share moments, share %string%.",
    "Simply %string%!",
    "Start the day with %string%.",
    "Stay cool with %string%.",
    "Step into the light with %string%.",
    "Swing your %string%.",
    "Take what you want, but leave %string% alone!",
    "Thanks %string%.",
    "The %string% community.",
    "The %string% effect.",
    "The %string% look.",
    "The %string% man.",
    "The %string% people.",
    "The %string% spirit.",
    "The %string% universe.",
    "The %string% way of life.",
    "The age of %string%.",
    "The American Way of %string%.",
    "The art of %string%.",
    "The best %string% in the world.",
    "The Future of %string%.",
    "The goddess made %string%.",
    "The gods made %string%.",
    "The ideal %string%.",
    "The magic of %string%.",
    "The one and only %string%.",
    "The original %string%.",
    "The Power of %string%.",
    "The president buys %string%.",
    "The queen buys %string%.",
    "The Queen of %string%.",
    "The secret of %string%.",
    "The Spirit of %string%.",
    "The view on %string%.",
    "The wonder has a name: %string%.",
    "There is no life without %string%.",
    "There's a bit of %string% in all of us.",
    "There's lots of fun in %string%.",
    "There's only one thing in the world I want and that is %string%.",
    "There's only one true %string%!",
    "Things go better with %string%.",
    "Think %string%.",
    "Think different, think %string%.",
    "Think. Feel. %string%.",
    "Truly %string%.",
    "Up, up and away with %string%.",
    "Way to go, %string%!",
    "What is %string%?",
    "When you say %string% you've said it all.",
    "Where the hell is %string%?",
    "Where's %string%?",
    "Where's your %string%?",
    "Who is %string%?",
    "Who wouldn't fight for %string%?",
    "With a name like %string%, it has to be good.",
    "World's finest %string%.",
    "Worldclass %string%!",
    "You better get inside %string%.",
    "You better get your %string% out.",
    "You can't beat %string%.",
    "You can't stop %string%.",
    "You don't want %string% as your enemy!",
    "You know when it's %string%.",
    "You wouldn't want to miss %string%."
);

# USAGE:
# /slogan <text>
# writes a slogan with "text" to the current channel

sub cmd_slogan {
    my ( $data, $server, $witem ) = @_;
    if ( !$server || !$server->{connected} ) {
        Irssi::print("Not connected to server");
        return;
    }
    if ( !$witem ) {
        Irssi::print("Use this command in a channel or pvt");
        return;
    }
    if ($data) {
        my $slogan = $slogans[ rand @slogans ];
        $slogan =~ s/%string%/$data/;
        $witem->command( "/SAY " . $slogan );
    }
}

Irssi::command_bind( 'slogan', 'cmd_slogan' );
